### ISSUE TITLE
Downloading attached file it is not named correctly

### ISSUE THREAD

**Issue by ChristianAE** [thewhitetulip/Tasks#20]
When downloading a file attached to a task, it is named with it's md5 hash.
Furthermore the extension is missing. Once I add the extension the file can be opened as expected.

When downloading a file attached to a task the downloaded file should be named as the original file including it's file extension.

I tested this in the current version using Chrome and Firefox.

On a side note: It would be nice to be able to upload a new revision of a file to an existing task.

**Comment by thewhitetulip** [comment]
Can you think of a solution? And then submit a PR?

**Comment by ChristianAE** [comment]
I am fairly new to Go and web development in general.

From my understanding instead of directly embedding a link to the file in the content, the link should point to some address which fires a GET request retrieving the original file name.

**Comment by thewhitetulip** [comment]
For learning web development in Go, you can read my book! I have written it for this scenario itself.

The thing is, when we upload a file, we take it's md5 and rename the file. Whenever we get the /file/md5 hash, we retrieve the file form the filesystem

What you'd need to do is, md5 the user given file name so that they don't put something malicious and then store it in the database opposite to the actual file name, and the next time a request for the file comes, do an md5 of the file name and select the user given file name from the database. I'll not fix this, you can go ahead and try. Let me know if you face challenges!

**Comment by crazcalm** [comment]
Do you mind if I try to solve this? I am also pretty new to Go, but this sounds like something I should learn how to do.

**Comment by thewhitetulip** [comment]
You are welcome to solve this! I am available if you are facing any issues.

**Comment by crazcalm** [comment]
@thewhitetulip I have having difficulty finding a place in the UI that allows you to download the previously uploaded content. If it does exist, can you post an image of where I can find it?

If it does not exist, then adding the appropriate file extensions to the content post the md5  hash (when saving it) will allow people who download it via left clicking and saving the image to be able to open the image (but the image name will still be the md5 hash name). Is that okay?

If there is a download link in the UI, then I can modify the database and create a mapping between the original file name and the md5 hash so that I can change the file name back to the original name when downloading. In any case, I still think the file extension should be added to the md5 hash name so that users can still left click download it and open the file. Is this option okay?

I was also having trouble finding the database schema. Which files are used to create the database?

Thanks in advance for your help!

**Comment by crazcalm** [comment]
@thewhitetulip I have having difficulty finding a place in the UI that allows you to download the previously uploaded content. If it does exist, can you post an image of where I can find it?

If it does not exist, then adding the appropriate file extensions to the content post the md5  hash (when saving it) will allow people who download it via left clicking and saving the image to be able to open the image (but the image name will still be the md5 hash name). Is that okay?

If there is a download link in the UI, then I can modify the database and create a mapping between the original file name and the md5 hash so that I can change the file name back to the original name when downloading. In any case, I still think the file extension should be added to the md5 hash name so that users can still left click download it and open the file. Is this option okay?

I was also having trouble finding the database schema. Which files are used to create the database?

Thanks in advance for your help!

**Comment by thewhitetulip** [comment]
schema.sql is the database schema. The db already has the mapping between tge .d5 and the file name + the extenaion, but it isn't being used now.

There is no download center! If you uplift pdf documebt in a task, you can download it from that task itself. Feel free to add any modifications, if u want to add a page for "uploaded files" that's fine as well. But I'd recommend that when we generate the HTML of a note which contains the uploaded file, check how we give the name to the file and then change the way files are retrieved in the notes. Let me know if you need any more help. Cheers.

**Comment by thewhitetulip** [comment]
Also, you can study from my book in case you are a newcomer to writing webapps

**Comment by r0nni3** [comment]
Hi @thewhitetulip,

Can I work on solving this issue?

**Comment by thewhitetulip** [comment]
Sure! If you are stuck, I'll help. You can read the Go book I've written it is on my github profile.

**Comment by r0nni3** [comment]
Thanks!

I believe I found the issue, but I have a doubt first.
When files are uploaded, a hash sum is generated (token) and stored on the DB along with the file name, but the actual file object is stored with this hash sum as the filename on the `/files` directory. What is this token intended use?

**Comment by thewhitetulip** [comment]
Token's use was to provide a link to the file without revealing its original name
