### ISSUE TITLE
issue when change html, js, css

### ISSUE THREAD

**Issue by PhanHaHus** [thewhitetulip/Tasks#26]
When I change html, js, css I need turn off server and reload server then new code appear. Why the server didn't auto receive new client code, sorry for my bad english

**Comment by thewhitetulip** [comment]
This doesn't happen for css and js. if you change css and js, then just refresh the page.

If you change the html, you have to restart the server because the server reads the html files once when it starts, so each change of html should restart the server.

We can modify the server to restart automatically, but it's complicated

**Comment by PhanHaHus** [comment]
At first, js and css need restart server too, I must put this line

http.Handle("/static/", http.FileServer(http.Dir("public")))

before this line

views.PopulateTemplates()

then refresh the page js and css work. 

ok with html I understand, thanks you for best structure :D

**Comment by thewhitetulip** [comment]
any time :) this project was created for teaching how to write webapps in Go, I hope you are referring to the book https://github.com/thewhitetulip/web-dev-golang-anti-textbook/
