### ISSUE TITLE
database Close function  doesnt use

### ISSUE THREAD

**Issue by glepnir** [thewhitetulip/Tasks#41]
Hi @thewhitetulip ,i saw you defined the [Close](https://github.com/thewhitetulip/Tasks/blob/master/db/tasks.go#L69) funtion to close the databse connection, but i didnt see you use this function ,why not close the database connection?

**Comment by thewhitetulip** [comment]
The close function is not required because we can't run the server without running the database. I should have added the close() function before the error handling while running the server though.

**Comment by glepnir** [comment]
@thewhitetulip  Does the connection to this database need to be closed after each query? Excessive query insert delete operation does not need to release the database connection?

**Comment by thewhitetulip** [comment]
Imagine you run github.com

When the user logs in, your server sends a database query to fetch user details.

Then the user logs in and clicks home button

Then the server sends a query to the database to fetch more details.

Think, do you want to close database connection after every query?

Also, did you read my tutorial?

**Comment by glepnir** [comment]
@thewhitetulip  yeah i read by  google translate.... i think i know your mean . 
But if too many accesses, do not set the database connection pool, will not cause blocking?

**Comment by thewhitetulip** [comment]
What I mean is, if you close the database connection for each request then you'll need to open database connection *every* single time your app hits the database, which will be every second the user does something. So, no. you don't close the database until your app server closes and that'll happen only when the server crashes

and blocking doesn't happen because that's the job of Go and Mysql to ensure it doesn't happen. 

also, we are opening one connection and querying on it. As of now, we have only one user so performance is of no concern. I am not an expert, but there will be various ways to ensure scalability

**Comment by glepnir** [comment]
thanks a lot !!

**Comment by thewhitetulip** [comment]
You are welcome.

**Comment by glepnir** [comment]
@thewhitetulip  do you have plan to make a new tutorial about the goroutine in action?

**Comment by thewhitetulip** [comment]
I have stopped coding in Go. My focus now is only on data science. So mostly not. Let's see in the future if I get time.
